package com.hfjy.ml.bean
import scala.beans.BeanProperty

/**
  * Created by kehailin on 2018-12-17.
  */
case class BatchModelBTeacherId(@BeanProperty override val dateTime: String = "",
                                @BeanProperty var student_id: Int = -1,
                                @BeanProperty var student_no: Int = -1,
                                @BeanProperty var order_id: Int = -1,
                                @BeanProperty var new_student_City_Class: Int = -1,
                                @BeanProperty var new_studentSource: Int = -1,
                                @BeanProperty var cross_sex: Int = -1,
                                @BeanProperty var new_new_studentSex: Int = -1,
                                @BeanProperty var new_studentPresentProvince: Int = -1,
                                @BeanProperty var subjectId: Int = -1,
                                @BeanProperty var grade_subject: Int = -1,
                                @BeanProperty var new_studentGrade: Int = -1,
                                @BeanProperty var new_examYear: Int = -1,
                                @BeanProperty var seniorSchoolInfo: Int = -1,
                                @BeanProperty var score_mean: Double = 0.0,
                                @BeanProperty var enableTrialCount: Int = -1,
                                @BeanProperty var new_seniorClassInfo: Int = -1,
                                @BeanProperty var new_classRank: Int = -1,
                                @BeanProperty var new_gradeRank: Int = -1,
                                @BeanProperty var haveAfterPlan: Int = -1,
                                @BeanProperty var new_selfEvaluation: Int = -1,
                                @BeanProperty var new_learningTarget: Int = -1,
                                @BeanProperty var province_byphone: Int = -1,
                                @BeanProperty var new_coil_in: Int = -1,
                                @BeanProperty var new_new_selfEvaluation: Double = 0.0,
                                @BeanProperty var effectiveCommunicationCount: Int = -1,
                                @BeanProperty var firstTrialCourse: Int = -1,
                                @BeanProperty var score_min: Double = 0.0,
                                @BeanProperty var score_max: Double = 0.0,
                                @BeanProperty var filled_new_student_City_Class: Int = -1,
                                @BeanProperty var teacher_id: Int = -1,
                                @BeanProperty var teacherSex: Int = -1,
                                @BeanProperty var teacherJobType: Int = -1,
                                @BeanProperty var new_teacher_City_Class: Int = -1,
                                @BeanProperty var new_new_teached_age: Int = -1,
                                @BeanProperty var new_teacherAge: Int = -1,
                                @BeanProperty var teachedOfficialStudentCount: Int = -1,
                                @BeanProperty var new_teacher_daily_audition_count: Double = 0.0,
                                @BeanProperty var new_collegeType: Int = -1,
                                @BeanProperty var real_new_rate: Double = 0.0,
                                @BeanProperty var new_teacherTrialCourseCount: Int = -1,
                                @BeanProperty var new_teacherPlanCourseInterval: Double = 0.0,
                                @BeanProperty var teachedTrialSuccessStudentCount: Int = -1,
                                @BeanProperty var teacher_audition_success_rate: Double = 0.0,
                                @BeanProperty var new_teacher_daily_audition_success_count: Double = 0.0,
                                @BeanProperty var lm_informal_teached_lesson_count: Int = -1,
                                @BeanProperty var taught_total_time: Int = -1,
                                @BeanProperty var first_tkod_tifl_count: Double = 0.0,
                                @BeanProperty var teachedTrialCourseCount: Int = -1,
                                @BeanProperty var filled_new_rate: Int = -1,
                                @BeanProperty var filled_new_teacher_City_Class: Int = -1,
                                @BeanProperty var trial_success_count: Int = -1,
                                @BeanProperty var refined_trial_success_rate: Double = 0.0,
                                @BeanProperty var filled_province_byphone: Int = -1,
                                @BeanProperty var filled_new_studentSource: Int = -1,
                                @BeanProperty var filled_seniorSchoolInfo: Int = -1,
                                @BeanProperty var filled_new_classRank: Int = -1,
                                @BeanProperty var filled_new_new_rate: Int = -1,
                                @BeanProperty var filled_new_coil_in: Int = -1,
                                @BeanProperty var y_proba_rf: Double = 0.0,
                                @BeanProperty var y_proba_xgb: Double = 0.0,
                                @BeanProperty var y_proba_gbdt: Double = 0.0,
                                @BeanProperty var y_proba_catboost: Double = 0.0,
                                @BeanProperty var final_score: Double = 0.0,
                                @BeanProperty var minmax_score: Double = 0.0,
                                @BeanProperty var batch: Int = -1,
                                @BeanProperty var version: String = "",
                                @BeanProperty var code: Int = 0,
                                @BeanProperty var message: String = ""
                               ) extends Time