package com.hfjy.ml.bean

import scala.beans.BeanProperty

/**
  * Created by kehailin on 2018-12-17.
  */
case class BatchModelBTeacherIdV2(@BeanProperty override val dateTime: String = "",
                                  @BeanProperty var teacher_id: Int = -1,
                                  @BeanProperty var student_grade: Int = -1,
                                  @BeanProperty var know_origin_discretize: Int = -1,
                                  @BeanProperty var coil_in_discretize: Int = -1,
                                  @BeanProperty var know_origin: Int = -1,
                                  @BeanProperty var apply_user_id: Int = -1,
                                  @BeanProperty var student_province_byphone: Int = -1,
                                  @BeanProperty var subject_type: Int = -1,
                                  @BeanProperty var is_teacher_college: Double = 0.0,
                                  @BeanProperty var his_success_rate: Double = 0.0,
                                  @BeanProperty var history_rate_bystudent: Double = 0.0,
                                  @BeanProperty var history_rate_bycontract: Double = 0.0,
                                  @BeanProperty var l3m_sucess_rate: Double = 0.0,
                                  @BeanProperty var before_20181201_sale_trial_suc_count: Int = -1,
                                  @BeanProperty var sucess_rate: Double = 0.0,
                                  @BeanProperty var score_mean: Double = 0.0,
                                  @BeanProperty var sale_trial_total_count: Int = -1,
                                  @BeanProperty var score_min: Double = 0.0,
                                  @BeanProperty var lm_sale_success_rate: Double = 0.0,
                                  @BeanProperty var history_trail_suc_cnt_bycontract: Int = -1,
                                  @BeanProperty var student_city_class_detail: Int = -1,
                                  @BeanProperty var sale_success_rate: Double = 0.0,
                                  @BeanProperty var day: Int = -1,
                                  @BeanProperty var teacher_work_year: Double = 0.0,
                                  @BeanProperty var exam_scores: Double = 0.0,
                                  @BeanProperty var l3m_taught_trial_student_cnt: Int = -1,
                                  @BeanProperty var l3m_teacher_submit_hw_cnt: Int = -1,
                                  @BeanProperty var l3m_teacher_hw_cnt: Int = -1,
                                  @BeanProperty var l3m_teacher_correct_hw_cnt: Int = -1,
                                  @BeanProperty var l3m_hw_submit_rate: Double = 0.0,
                                  @BeanProperty var l3m_hw_correct_rate: Double = 0.0,
                                  @BeanProperty var l3m_student_relative: Double = 0.0,
                                  @BeanProperty var l3m_taught_official_student_cnt: Int = -1,
                                  @BeanProperty var teacherJobType: Int = -1,
                                  @BeanProperty var y_proba_rf: Double = 0.0,
                                  @BeanProperty var y_proba_xgb: Double = 0.0,
                                  @BeanProperty var y_proba_gbdt: Double = 0.0,
                                  @BeanProperty var y_proba_lgb: Double = 0.0,
                                  @BeanProperty var y_proba_catboost: Double = 0.0,
                                  @BeanProperty var final_score: Double = 0.0,
                                  @BeanProperty var minmax_score: Double = 0.0,
                                  @BeanProperty var batch: Int = -1,
                                  @BeanProperty var version: String = "",
                                  @BeanProperty var code: Int = 0,
                                  @BeanProperty var message: String = ""
                                 ) extends Time